# minimal config for the mail details.

spring:
  application:
    name: watchdog
  mail:
    host: smtp.gmail.com
    port: 587
    username: chethancn82@gmail.com
    #add your encrypted password here
    # ( utilize config/EncryptPassword.java to encrypt the password)
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


watchdog:
  check-interval: 600000         # Initial value
  summary-time: 0 0 11 * * WED  # Initial value
  email-recipients: # Add Recipients here
logging:
  level:
    org.jasypt: DEBUG
    com.charite.watchdog.service: DEBUG
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES