spring:
  application:
    name: watchdog
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:chethancn82@gmail.com}
    password: ${MAIL_PASSWORD:fdaiqnjqyeizulvy} # Use env vars in production
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

watchdog:
  check-interval: 30000  # 30 seconds for testing
  summary-interval: 7d # Summary email frequency (e.g., 30 seconds)
  email:
    recipients: ${EMAIL_RECIPIENTS:chethanrao82@gmail.com}
    sender: ${EMAIL_SENDER:chethancn82@gmail.com}


logging:
  level:
    com.charite.watchdog: DEBUG  # Show DEBUG, INFO, WARN, ERROR from your package