# minimal config for the mail details.

spring:
  application:
    name: watchdog
  mail:
    host: smtp.gmail.com
    port: 587
    username: chethancn82@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


watchdog:
  check-interval: 60000        # Initial value
  summary-time: 0 00 10 * * MON  # Initial value
  email-recipients: chethanrao82@gmail.com
logging:
  level:
    com.charite.watchdog.service: DEBUG